# constant
GENRE_JAZZ = 0
GENRE_DISCO = 1
GENRE_CLASSICAL = 2
GENRE_ROCK = 3

genre_inst = {GENRE_JAZZ:[65,0,36,40],GENRE_DISCO:[54,53,36,40],GENRE_CLASSICAL:[40,48,43,61], GENRE_ROCK:[29,5,34,0]}
genre_drum = {GENRE_JAZZ:"120 Bossa Hihat.mid",GENRE_DISCO:"130 DISCOA.mid",GENRE_CLASSICAL:"120 Bossa Hihat.mid", GENRE_ROCK:"70 Ridebell sync groove.mid"}
genre_str = {GENRE_JAZZ:"Jazz",GENRE_DISCO:"Disco",GENRE_CLASSICAL:"Classical", GENRE_ROCK:"Rock"}